#! /usr/bin/env bash

set -e

PGPASSWORD=$ADMIN_PASSWORD psql -h $DB_HOSTNAME -p $DB_PORT -U $ADMIN_USERNAME -d postgres <<-SQL
CREATE USER $DB_USERNAME WITH PASSWORD '$DB_PASSWORD';
CREATE DATABASE $DB_DATABASE OWNER $DB_USERNAME;
GRANT CREATE ON DATABASE $DB_DATABASE TO $DB_USERNAME;
GRANT agdc_admin TO $DB_USERNAME;
SQL


