version: '3'
services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

  redis:
    image: 'redis'
    command: redis-server --requirepass devpassword
    ports:
      - '6379:6379'
      
  indexing:
    build: .
    env_file:
      - .env
    command: celery -A restcube.tasks.indexing.celery worker

  tasks:
    build: .
    env_file:
      - .env
    command: celery -A restcube.tasks.data.celery worker

  restcube:
    build: . 
    env_file:
      - .env
    depends_on:
      - postgresql
    ports:
      - "8000:8000"
